FROM java:8
VOLUME /tmp
ADD spring-cloud-producer-0.0.1.jar app.jar
RUN bash -c 'touch /app.jar'
ENV APP_OPTS=""
ENTRYPOINT ["sh","-c","java -Djava.security.egd=file:/dev/./urandom -jar /app.jar $APP_OPTS"]
