apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - name: 'http-8000'
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080  #指定主机任意端口30000-32767
  selector:
    app: gateway